### ISSUE TITLE
Double-curly-brace syntax for interpolation isn't supported

### ISSUE THREAD

**Issue by patbl** [wazeHQ/yaml-validator#6]
There are two syntaxes for interpolation in locale files, `%{var}` and `{{var}}`. Only the first is supported. YAML Validator thinks the second is a syntax error:

```yml
# en.yml
en:
  foo: "{{lol}}"

# pt.yml
pt:
  foo: "{{lol}}"
```

```
$ yaml-validator validate .
Validating ....


pt.yml: foo: invalid syntax '{{lol}'

found 1 error(s)
```

This repository doesn't have much recent activity. Are pull requests still welcome? This gem seems as though it could be very useful.
